name: Publish a Hugo site
description: Builds a Hugo website and deploys it into the gh-pages branch.

inputs:
  access_token:
    description: "Token for accessing the theme components private repository"
    required: true
  deploy_key:
    description: "SSH deploy key"
    required: true

runs:
  using: composite
  steps:
    # see https://github.com/actions/checkout
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.access_token }}
        submodules: true

    # see https://github.com/peaceiris/actions-hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --gc --minify
      shell: bash

    # see https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ inputs.deploy_key }}
        publish_branch: gh-pages
        publish_dir: ./public
